### ISSUE TITLE
Not grouped attribute list incomplete when using complete OWL International release

### ISSUE THREAD

**Issue by kaicode** [IHTSDO/snomed-owl-toolkit#26]
The MRCM Attribute Domain Reference Set is used to lookup the set of attributes which should not be self grouped when converting stated relationships to axiom during the classification process. This is failing to work correctly when classifying an extension using the July International Edition release.
The reason is because stated relationships within the International Edition are used to lookup the SNOMED content type but these are no longer present.

**Comment by CoderMChu** [comment]
The fix for this is committed in develop branch:

https://github.com/IHTSDO/snomed-owl-toolkit/commit/62aa1ae71564d16be35304539b50f5bff2896fe7

**Comment by kaicode** [comment]
Passes testing. The 24 active ungrouped MRCM Attribute Domain reference components are now loaded correctly from the July 2019 International Edition member release.
