### ISSUE TITLE
Synonyms for the Dutch Patient Friendly terms

### ISSUE THREAD

**Issue by AJKellmann** [IHTSDO/snomed-owl-toolkit#30]
Hi @kaicode,

I'm trying to use the Dutch version of the Snomed ontology to search for synonyms.
Therefore I would also like to use the "Patient Friendly terms" as synonyms using skos:altLabel.

Here's an excerpt of the description file:

```
id	effectiveTime	active	moduleId	conceptId	languageCode	typeId	term	caseSignificanceId

126811000146112	20190331	1	15561000146104	473011001	nl	900000000000013009	allergieën	900000000000448009
126831000146117	20190331	0	15561000146104	363418001	nl	900000000000013009	alvleesklierkanker	900000000000020002
126931000146113	20190331	0	15561000146104	363354003	nl	900000000000013009	baarmoederhalskanker	900000000000020002
126941000146117	20190331	0	15561000146104	371973000	nl	900000000000013009	baarmoederkanker	900000000000020002
```

I used the newest version (2.8.0) of the owl toolkit to translate the rf2 files into owl.
To get the patient friendly synonyms I added 2 IDs to the language-refset-dialect-map.properties file:
>15551000146102=nl 
>15561000146104=nl 

Then I used the following command to run the program:
`java -jar snomed-owl-toolkit-2.8.0-executable.jar -rf2-to-owl -rf2-snapshot-archives ./SnomedCT_Netherlands_PatientFriendlyExtensionRelease_PRODUCTION_20190331T120000Z.zip`                                                                                    

The Programm reports that it has found 2 relationships and 611 descriptions:
```
2019-11-28 09:20:05,069 [INFO  ] [pool-1-thread-1] org.ihtsdo.otf.snomedboot.ReleaseImporter - 2 relationships read from sct2_Relationship_Snapshot_NL-PatientFriendly_20190331.txt
2019-11-28 09:20:05,084 [INFO  ] [pool-1-thread-3] org.ihtsdo.otf.snomedboot.ReleaseImporter - 611 descriptions read from sct2_Description_Snapshot_NL-PatientFriendly_20190331.txt
```
But the output file just consists of the 2 Class entries:

```
Prefix(:=<http://snomed.info/id/>)
Prefix(owl:=<http://www.w3.org/2002/07/owl#>)
Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>)
Prefix(xml:=<http://www.w3.org/XML/1998/namespace>)
Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>)
Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>)
Prefix(skos:=<http://www.w3.org/2004/02/skos/core#>)


Ontology(<http://snomed.info/sct/900000000000207008>
<http://snomed.info/sct/900000000000207008/version/20191128>

Declaration(Class(:15551000146102))
Declaration(Class(:15561000146104))
Declaration(Class(:900000000000443000))
Declaration(Class(:900000000000506000))
Declaration(AnnotationProperty(skos:altLabel))


############################
#   Classes
############################

# Class: <http://snomed.info/id/15551000146102> (Patient-friendly Dutch language reference set (foundation metadata concept))

AnnotationAssertion(rdfs:label :15551000146102 "Patient-friendly Dutch language reference set (foundation metadata concept)"@nl)
AnnotationAssertion(skos:altLabel :15551000146102 "Patient-friendly Dutch language reference set"@nl)
SubClassOf(:15551000146102 :900000000000506000)

# Class: <http://snomed.info/id/15561000146104> (SNOMED CT Dutch module for patient-friendly descriptions (core metadata concept))

AnnotationAssertion(rdfs:label :15561000146104 "SNOMED CT Dutch module for patient-friendly descriptions (core metadata concept)"@nl)
AnnotationAssertion(skos:altLabel :15561000146104 "SNOMED CT Dutch module for patient-friendly descriptions"@nl)
SubClassOf(:15561000146104 :900000000000443000)
```

What needs to be done to receive the dutch friendly Terms as annotations?

**Comment by kaicode** [comment]
Hi @AJKellmann it looks like the extension package only contains descriptions and one or two concepts. 

When converting an extension all the release files that the extension depends on are also required as input.

The date in the extension shown in 20190331 so I assume it is dependant on the Jan 2019 International Edition. If that is the only dependency the command would be something like:
```
java -Xms4g -jar snomed-owl-toolkit-2.8.0-executable.jar -rf2-to-owl -rf2-snapshot-archives SnomedCT_InternationalRF2_PRODUCTION_20190131T120000Z.zip,SnomedCT_Netherlands_PatientFriendlyExtensionRelease_PRODUCTION_20190331T120000Z.zip
```

If the extension is also dependant on another extension that should be given as input too. The `-rf2-snapshot-archives` parameter takes a comma separated list of paths to RF2 archives.

I hope that helps.
Kai

**Comment by AJKellmann** [comment]
@kaicode 
Thanks, adding the different snapshot archives helped to get the Dutch and the Dutch friendly terms.
As you suggested, I also added the international version to the list.
Since I just have the International version 20190731, I used that one.

It mostly seemed to work, but a major part of the English labels is missing now.
During the conversion process I got an error message:

```
2019-11-28 11:39:47,018 [ERROR ] [pool-1-thread-10] org.ihtsdo.otf.snomedboot.ReleaseImporter - Failed to read or process lines.
java.lang.NullPointerException
	at org.snomed.otf.owltoolkit.taxonomy.SnomedTaxonomy.setDescriptionAcceptability(SnomedTaxonomy.java:259)
	at org.snomed.otf.owltoolkit.taxonomy.SnomedTaxonomyLoader.newReferenceSetMemberState(SnomedTaxonomyLoader.java:197)
	at org.ihtsdo.otf.snomedboot.factory.filter.LatestEffectiveDateFilter.newReferenceSetMemberState(LatestEffectiveDateFilter.java:55)
	at org.ihtsdo.otf.snomedboot.ReleaseImporter$ImportRun.lambda$loadRefsets$3(ReleaseImporter.java:469)
	at org.ihtsdo.otf.snomedboot.ReleaseImporter$ImportRun.readLines(ReleaseImporter.java:554)
	at org.ihtsdo.otf.snomedboot.ReleaseImporter$ImportRun.lambda$readLinesCallable$4(ReleaseImporter.java:488)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-11-28 11:39:47,197 [INFO  ] [pool-1-thread-4] org.ihtsdo.otf.snomedboot.ReleaseImporter - 225 reference set members read from sct2_sRefset_OWLExpressionSnapshot_NL_20190331.txt
2019-11-28 11:39:47,620 [ERROR ] [pool-1-thread-9] org.ihtsdo.otf.snomedboot.ReleaseImporter - Failed to read or process lines.
java.lang.NullPointerException
2019-11-28 11:39:47,673 [ERROR ] [pool-1-thread-6] org.ihtsdo.otf.snomedboot.ReleaseImporter - Failed to read or process lines.
java.lang.NullPointerException
```

This does not happen when I just convert the international version.
I can merge the two ontologies using Protege, but that's still a workaround.

**Comment by kaicode** [comment]
Thanks for the stack trace, that helps.
This line is causing the null pointer:
https://github.com/IHTSDO/snomed-owl-toolkit/blob/master/src/main/java/org/snomed/otf/owltoolkit/taxonomy/SnomedTaxonomy.java#L259

This indicates that there is an active language reference set entry for a description which does not exist or is not active. If the Dutch extensions are dependent on the January 2019 International Edition they may be referencing content which is active January but no longer active in the July package you are using. 

I recommend using the January 2019 International package which I imagine the Dutch extension release has been built and validated against.

**Comment by AJKellmann** [comment]
Thanks a lot, with the January package everything went well.
I think we can close this Issue now.
