### ISSUE TITLE
2.9.0 version with "An Ontology file can not be produced."

### ISSUE THREAD

**Issue by erfelipe** [IHTSDO/snomed-owl-toolkit#35]
Hi @kaicode ,
I'm try to use 2.9.0 toolkit version, and I receive this problem (from log):

2020-01-07 21:29:53,973 [INFO ] [main] org.snomed.otf.owltoolkit.taxonomy.SnomedTaxonomyBuilder - 0 active axioms loaded
org.snomed.otf.owltoolkit.conversion.ConversionException: No Stated Relationships or Axioms were found. An Ontology file can not be produced.
at org.snomed.otf.owltoolkit.conversion.RF2ToOWLService.convertRF2ArchiveToOWL(RF2ToOWLService.java:51)
at org.snomed.otf.owltoolkit.Application.rf2ToOwl(Application.java:145)
at org.snomed.otf.owltoolkit.Application.run(Application.java:88)
at org.snomed.otf.owltoolkit.Application.main(Application.java:53)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)

Can you try the RF2 conversion in your machine? The command line that I'm try to use, is: java -jar snomed-owl-toolkit-2.9.0-executable.jar -rf2-to-owl -rf2-snapshot-archives SnomedCT_InternationalRF2_PRODUCTION_20190731T120000Z.zip

Regards,

**Comment by kaicode** [comment]
Hi @erfelipe,
I'm not sure how this happened. Could you paste the full command line output please?
Could use https://gist.github.com/
Thanks.

**Comment by erfelipe** [comment]
Hi @kaicode ,

I'm try again now, and there is:
https://gist.github.com/cc337684618f3725b77a9011c46ebaaa#file-an ontology file can not be produced-txt

If you need a different command line, with "debug" just write the line to try.

Thanks again,

**Comment by kaicode** [comment]
Hi @erfelipe,

I'm not able to reproduce the issue you are seeing.
This is my output - https://gist.github.com/kaicode/435cd498b57fc7346dc9e067f192e628

What version of java are you using? It has been tested with version 8 and 11.
Maybe it's running out of memory. Try adding 4G min and enabling debug:
```
java -Xms4g -jar snomed-owl-toolkit-2.9.0-executable.jar -rf2-to-owl -rf2-snapshot-archives SnomedCT_InternationalRF2_PRODUCTION_20190731T120000Z.zip -debug
```

**Comment by erfelipe** [comment]
Thanks @kaicode ,

I'll try to use your command line with increase memory.
My config Java is: 

java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode) 

Thanks.

**Comment by erfelipe** [comment]
@kaicode !

Works now! Works beautiful !  The memory of Java was the problem. 
In this version I have label's with skos version! Really great because I'm using querys in RF2 direct. (I migrate the TXT's to sqLite database to use it).

Thanks !!

**Comment by erfelipe** [comment]
@kaicode ,

May I ask you something else here? If you can't answer, that's fine. But when you generate OWL to build the hierarchical structure, do you read through the refset table's owlExpression? Using a parse in "ObjectIntersectionOf"?
And labels, do you consider the same conceptID in Description?

Thanks anyway.

**Comment by kaicode** [comment]
Hey. It's open source, we can talk about everything! 😄

Yes, we read all the owlExpression strings from the axiom refset in the SnomedTaxonomyLoader class [here](https://github.com/IHTSDO/snomed-owl-toolkit/blob/2.9.0/src/main/java/org/snomed/otf/owltoolkit/taxonomy/SnomedTaxonomyLoader.java#L161).

We use the java OWL-API from Stanford University ([quoted in the pom file](https://github.com/IHTSDO/snomed-owl-toolkit/blob/2.9.0/pom.xml#L32)) to build an Ontology object which holds everything [here](https://github.com/IHTSDO/snomed-owl-toolkit/blob/2.9.0/src/main/java/org/snomed/otf/owltoolkit/ontology/OntologyService.java#L85).

We also read in the descriptions and language reference sets to create the annotations. They are added to the Ontology object [here](https://github.com/IHTSDO/snomed-owl-toolkit/blob/2.9.0/src/main/java/org/snomed/otf/owltoolkit/ontology/OntologyService.java#L351). The OWL-API sorts everything nicely and provides a method to serialise everything to disk.

Does that answer your question?

Kind regards,
Kai

**Comment by erfelipe** [comment]
@kaicode ,

Really thanks for the tips and the code indication. I have already programmed in basic Java, far from your level. 
Currently the academic project I'm doing is in Python, it won't be worth looking for an interface for owl-api in Python, because I don't need to generate owl, its toolkit does it perfectly and helps me validate my queries. That's why I've been using owl, open it in Protégé and compare it to my sqLite queries inside Python.

I need that, given a class, I discover its hierarchy and the terms associated with it (by axiom and labels). This basically.

Maybe it's worth it to do a simpler parse, in Python, I'm going to try it.

Anyway, thank you very much for your support and success in your development.

A hug,
Sincerely,

**Comment by kaicode** [comment]
Bear in mind that the OWL axioms and the Ontology file generated by this tool are the _stated form_ of the SNOMED CT classes. Our authors use style of modeling called "proximal primitive modeling" where the stated parents are very high level and the classifier/reasoner is used to choose a more specific and meaningful parent. We distribute those inferred relationships in the inferred relationships file (e.g. sct2_Relationship_Snapshot_INT_20190731.txt) which is a very simple format of source (class), type (attribute), target (class) tripples. You could classify the stated ontology file in Protégé by switching on the reasoner. We use the ELK reasoner to classify SNOMED CT in our tooling but others may work. The inferred form after the classifier has run will give the parents you can see by default in the public [SNOMED CT browser](https://browser.ihtsdotools.org/).

All the best with your project! 😸

**Comment by erfelipe** [comment]
Thanks for this explanation @kaicode  ,

From the documentation I did not see it this way. I also didn't think you were running the reasoner at the time of OWL generation for this reason! This really comes as a big surprise, that the team does not define hierarchies by human interpretation, but lets the reasoner decide.

But @kaicode , if for my urgency of the project, I consider multiple inheritance, is it conceptually correct? In this example axiom below:

EquivalentClasses (: 238594009 ObjectIntersectionOf (: 247446008: 418363000: 64572001 ObjectSomeValuesFrom (: 609096000 ObjectIntersectionOf (ObjectSomeValuesFrom (: 116676008: 409777003) ObjectSomeValuesFrom (: 3636370000))

May I infer that the concept 238594009 is a child of three classes: 247446008: 418363000: 64572001?

That would help me a lot because I can parser this, and given a term, figure out its hierarchy and associated terms (various descriptions).

Thanks !

**Comment by kaicode** [comment]
Stating only high level parents and using the reasoner to organise the hierarchy allows the ontology to be reorganised easily by changing the modeling of the defined concepts. It also validates the modeling of each new concept as it's added because the author checks the inferred parents. If the inferred parents are not correct then the modeling (stated axioms) need adjusting. The authors strive to model in this way but they are pragmatic and there is a lot of older content which was created when a different strategy was in place.

Yes you are correct. Concept _238594009 | Desiccation eczema (disorder) |_ does have three stated parents. We can see this in the browser when we switch to the Stated view:
<img width="759" alt="Screenshot 2020-01-13 at 10 53 26" src="https://user-images.githubusercontent.com/2010517/72250269-1d1d3580-35f3-11ea-93b1-581972d7a141.png">

https://browser.ihtsdotools.org/?perspective=full&conceptId1=238594009&edition=MAIN/2019-07-31&release=&languages=en

There is a hidden function in the OWL Toolkit which parses the OWL Axioms and outputs the triples in a stated relationship TSV format. It should only be used for experimentation. There is a loss of information because if a concept has multiple axioms or GCI axioms these can not be expressed well in this format. To access this function use `-rf2-owl-to-stated` rather than `-rf2-to-owl`. I am not able to offer support on this function because it's a throwaway thing we wrote as a workaround for some statistics we needed but it may be of some use to you.

I hope that helps. Kind regards,
Kai

**Comment by kaicode** [comment]
An example of multiple axioms.. concept _432685000 | Product containing methylcellulose in oral dose form (medicinal product form) |_ has two axioms because it has two distinct definitions. If these are converted to stated relationships the triples from each axiom will be combined. There is no axiom field in the stated relationship format.

**Comment by erfelipe** [comment]
Precious information that you are giving me @kaicode .

Nor did I think I could have multiple axioms for the same concept. I will work with an array to consider in parse.

Really thanks for the tips.

Best wishes,

**Comment by kaicode** [comment]
Sure, go ahead. Or you are welcome to create a new issue ticket just for your question. Whichever.
