### ISSUE TITLE
I met a problem in parsing the owl file generated by snomed-owl-toolkit

### ISSUE THREAD

**Issue by denglizong** [IHTSDO/snomed-owl-toolkit#39]
Dear author, 
         I have successfully converted snomed ct RF2 production into OWL format, thank you! However, I found common owl parsers like owlready2, pronto, ontospy, can not parse the snomed owl file. For example, 
    the error message from owlready 2 is "OwlReadyOntologyParsingError: NTriples parsing error (or unrecognized file format) in sct.owl, line 1."
     the error message from pronto is "ValueError: could not find a parser to parse 'sct.owl'";
     
     Would you please give me some suggestions for parsing snomed.ct owl file? Thank you very much.
     Best Regards,

**Comment by AJKellmann** [comment]
Hi denglizong,

I'm a user, not the author of this tool, Kai might have more insights into the technical details.

When I tried to load it into a Virtuoso server a few weeks ago, I was facing a similar problem with the resulting Snomed owl file.

My solution was to open the file in Protege, and save it as owl file with turtle syntax.
The resulting file in turtle syntax could then be parsed/imported seamlessly into Virtuoso.
(Protege Version 4.3 didn't work, but Protege Version 5.5 did the job.)

Best Regards
Alexander

**Comment by denglizong** [comment]
Alexander, 
       Your suggestion has solved my problem. Thanks for your help!  
       Best Regards,
       Lizong

**Comment by kaicode** [comment]
Hi @denglizong,

The SNOMED OWL Toolkit outputs the OWL file using [OWL Functional Syntax](https://www.w3.org/TR/owl2-syntax/).
I am reading that "Owlready2 can: - Import ontologies in RDF/XML, OWL/XML or NTriples format" so it's likely that it's can't parse Functional Syntax.

Thank you @denglizong for providing a workaround 😄 

Kind regards,
Kai

**Comment by denglizong** [comment]
thank you @kaicode for your message! Now I understand why this problem happens.

**Comment by ab-prog1** [comment]
Dear friends, please guide me
I got permission to use snomd but I can't load it into protege.
And apparently it has to become an owl. Can anyone tell me how to convert? thank you

**Comment by kaicode** [comment]
Hi @ab-prog1, 

You can convert a SNOMED CT Edition RF2 archive to an OWL ontology file to load into Protege using this project.

Download an `*-executable.jar` file from the [releases page](https://github.com/IHTSDO/snomed-owl-toolkit/releases) and then follow [these instructions](https://github.com/IHTSDO/snomed-owl-toolkit#snomed-rf2-to-owl-file-conversion).

If you are converting the International Edition or US Edition you only need one SNOMED CT input file. If you are converting an extension then you will need to provide the International Edition and the extension RF2 files as input. Just shout if you have any further questions.

Kind regards,
Kai

**Comment by ab-prog1** [comment]
Dera Kai Kewley
Thank you for your help
I have these 3 files
-SnomedCT_InternationalRF2_PRODUCTION_20200731T120000Z.zip
-SnomedCT_USEditionRF2_PRODUCTION_20200901T120000Z.zip
-snomed-owl-toolkit-2.9.0-executable
And I run the following commands but it gives an error message.
    java -Xms4g -jar snomed-owl-toolkit-2.9.0-executable.jar -rf2-to-owl -rf2-snapshot-Archives 
    ../
![1](https://user-images.githubusercontent.com/72790990/98959312-71d75880-2503-11eb-8592-9693c71c4bdb.jpg)
snomedCT_InternationalRF2_PRODUCTION_20200731T120000Z.zip

**Comment by kaicode** [comment]
The US Edition archive contains all the content of the International Edition so only one argument is needed.
The parameters are case sensitive. Try this:
```
java -Xms4g -jar snomed-owl-toolkit-2.9.0-executable.jar -rf2-to-owl -rf2-to-owl -rf2-snapshot-archives ../../releases/SnomedCT_USEditionRF2_PRODUCTION_20200901T120000Z.zip
```

**Comment by ab-prog1** [comment]
Dera Kai Kewley
Thank you for your help
After executing the commands, message number 1 was printed
Then create an owl file. But after loading it in protege, image 2 and 3 are empty ontology.

**Comment by ab-prog1** [comment]
Dera Kai Kewley
Thank you for your help
After executing the commands, message number 1 was printed
Then create an owl file. But after loading it in protege, image 2 and 3 are empty ontology.
![1](https://user-images.githubusercontent.com/72790990/99068145-3cd31080-25ac-11eb-9259-fdb5042cdc1f.png)
![2](https://user-images.githubusercontent.com/72790990/99068155-40ff2e00-25ac-11eb-8774-9b3c20f14e03.png)
![3](https://user-images.githubusercontent.com/72790990/99068168-4492b500-25ac-11eb-99b8-3a69d0bae051.png)
![4](https://user-images.githubusercontent.com/72790990/99068179-478da580-25ac-11eb-9c12-330823917318.png)

**Comment by kaicode** [comment]
@ab-prog1 you probably have a good ontology file. You may need to assign more memory to Protégé for this large ontology to be loaded successfully. See this [page about setting Protégé memory / heap size](https://protegewiki.stanford.edu/wiki/Setting_Heap_Size).

**Comment by ab-prog1** [comment]
Dear Kai Kewley
Thank you for your help
My problem is solved.
best regards

**Comment by acadTags** [comment]
> Hi denglizong,
> 
> I'm a user, not the author of this tool, Kai might have more insights into the technical details.
> 
> When I tried to load it into a Virtuoso server a few weeks ago, I was facing a similar problem with the resulting Snomed owl file.
> 
> _My solution was to open the file in Protege, and save it as owl file with turtle syntax._ The resulting file in turtle syntax could then be parsed/imported seamlessly into Virtuoso. (Protege Version 4.3 didn't work, but Protege Version 5.5 did the job.)
> 
> Best Regards Alexander

Thanks. That works for me - saved as `OML/XML Syntax`.
