### ISSUE TITLE
Contents of release-zipfile

### ISSUE THREAD

**Issue by ronaldcornet** [IHTSDO/snomed-owl-toolkit#4]
Two questions: 

Which are the constraints regarding contents of the Snapshot.zip?

I get a 0-byte owl-files, but seemingly no errors:

Creating Ontology using the following options:
Snapshot archives: [SnomedCT_InternationalRF2.zip]
Delta archive: -none-
Ontology URI: http://snomed.info/sct/900000000000207008
Ontology Version: 20180501
Include FSN Annotations: true

2018-05-01 14:51:15,037 [INFO ] [main] org.snomed.otf.owltoolkit.conversion.RF2ToOWLService - Loading RF2 files

I've tried both zipping the "Snapshot" folder from the release, as well as the "Terminology folder". Both gave the same result.

**Comment by kaicode** [comment]
Hi @ronaldcornet,
The snomed-boot library within the owl toolkit is looking for the following files:
- sct2_Concept_Snapshot*.txt
- sct2_Description_Snapshot*.txt
- sct2_StatedRelationship_Snapshot*.txt

Plus some reference sets:
- der2_*MRCM*Snapshot*.txt (Optional)
- der2_*Axiom*Snapshot*.txt (Optional)

The can be in any folder within the zip and could be prefixed with "x" which is the format for technical previews.

If it can't find the concept, or description file you should get an error like:
> FileNotFoundException: No Concept RF2 file found.

Feel free to email me your zip (via google drive or dropbox or something if it's too big) and I'll diagnose it.

**Comment by ronaldcornet** [comment]
Argh, I had gzipped one of the .txt files (relationships), so the set of .txt files was incomplete. Now it works. It would be great if missing necessary files would be indicated.
Sorry for this bug on my end!

**Comment by kaicode** [comment]
It's nice to hear it works on Windows. Thank you for testing.
