### ISSUE TITLE
How to generate NNF from SNOMED CT international Download to TXT File

### ISSUE THREAD

**Issue by kluthr1** [IHTSDO/snomed-owl-toolkit#40]
Hi,

I am unfamiliar with your software, and I would like to generate the NNF relationships to a txt file from the Snomed CT international download. As suggested from your readme, I ran the following command but had returned with two empty txt files. I would appreciate the help if it isn't an inconvenience. 
`java -Xms4g -jar snomed-owl-toolkit*executable.jar -classify -rf2-snapshot-archives SnomedCT_InternationalRF2_PRODUCTION_20200309T120000Z.zip`

Thanks!

**Comment by CoderMChu** [comment]
@kluthr1 Empty text files are expected as the published release (SnomedCT_InternationalRF2_PRODUCTION_20200309T120000Z.zip) has already been classified. It would be wrong to have new classification results. You need to add changes to the content (axioms or relationships) and use -rf2-authoring-delta-archive to re-classify.
Hope this helps and let me know if you have further questions.

**Comment by kaicode** [comment]
The pre-classified Necessary Normal Form can be found in the `sct2_Relationship_Snapshot_xxx.txt` file of the International release. 

For the March release this is: `SnomedCT_InternationalRF2_PRODUCTION_20200309T120000Z/Snapshot/Terminology/sct2_Relationship_Snapshot_INT_20200309.txt`. 

Running the classify function as you have done and receiving blank output proves that the NNF in that file is correct and complete. 

If you would like to test this further some rows can be removed from that file. When the classification function is run the missing rows will be generated in the output. The classification function is not able to generate the id or assign the moduleId but the other rows will be correct.

**Comment by kaicode** [comment]
Closing this because it has been answered and no further questions raised.
