### ISSUE TITLE
Spanish dialect

### ISSUE THREAD

**Issue by alanponce** [IHTSDO/snomed-owl-toolkit#47]
I run this command for aSNOMED CT in Spanish released on October 2020

java -jar snomed-owl-toolkit-2.9.0-executable.jar -rf2-to-owl -rf2-snapshot-archives SnomedCT_SpanishRelease-es_PRODUCTION_20201031T120000Z.zip 

And I got this error:

2020-12-12 17:47:15,978 [WARN  ] [main] org.snomed.otf.owltoolkit.ontology.OntologyService - Please add language reference set 450828004 to language-refset-dialect-map.properties and recompile. The dialect ISO code could not be appended to the annotations because it was not found.

is it because a language-refset-dialect-map.properties in Spanish need to be added? Could you please help me

**Comment by kaicode** [comment]
Hi @alanponce,
We've just published a release with the Spanish language reference set included.
https://github.com/IHTSDO/snomed-owl-toolkit/releases/tag/2.10.1

When generating an Ontology file please supply the Spanish release, that contains the translations, and the dependant International release, that contains the concepts, like this:
```
java -jar snomed-owl-toolkit-2.10.0-executable.jar -rf2-to-owl -rf2-snapshot-archives SnomedCT_SpanishRelease-es_PRODUCTION_202010310T120000Z.zip,SnomedCT_InternationalRF2_PRODUCTION_20200731T120000Z.zip 
```

All terms will be included in the generated ontology. The Spanish terms will have the Spanish ISO two character language code `@es`:
```
# Class: <http://snomed.info/id/1001000087107> (Ultrasonography of calf of right lower leg (procedure))

AnnotationAssertion(rdfs:label :1001000087107 "Ultrasonography of calf of right lower leg (procedure)"@en)
AnnotationAssertion(rdfs:label :1001000087107 "ecografía de pantorrilla derecha (procedimiento)"@es)
AnnotationAssertion(skos:altLabel :1001000087107 "Ultrasound of calf of right lower leg"@en)
AnnotationAssertion(skos:altLabel :1001000087107 "Ultrasound scan of calf of right lower leg"@en)
AnnotationAssertion(skos:prefLabel :1001000087107 "Ultrasonography of calf of right lower leg"@en)
AnnotationAssertion(skos:prefLabel :1001000087107 "ecografía de pantorrilla derecha"@es)
EquivalentClasses(:1001000087107 ObjectIntersectionOf(:71388002 ObjectSomeValuesFrom(:609096000 ObjectIntersectionOf(ObjectSomeValuesFrom(:260686004 :278292003) ObjectSomeValuesFrom(:405813007 :722116009)))))
```

Kind regards,
Kai Kewley
