### ISSUE TITLE
Concept model object attribute (762705008) included as class and as object property

### ISSUE THREAD

**Issue by fanavarro** [IHTSDO/snomed-owl-toolkit#49]
Hi everyone.
First, I would like to thank you for making available this useful tool. I am writing this issue because I've found that the concept 762705008 | Concept model object attribute (attribute) | is being included as owl class as well as object property (tested on july 2020 international edition):
![imagen](https://user-images.githubusercontent.com/11376639/119487875-2f1bf600-bd5a-11eb-9da8-19bf2288d22c.png)

Although I can edit the ontology in Protege editor, and access programmatically through the owlapi, there are other tools that complain about having an entity annotated as class and object property at the same time. For example, owlready2 for python throws the following error:
`TypeError: https//snomed.info/id762705008 belongs to more than one entity types (cannot be both a property and a class/an individual)`
I am not sure if this is due to a modelling error at the RF2 side, or a conversion error at the snomed-owl-kit side.
Thanks in advance!

**Comment by kaicode** [comment]
Hi @fanavarro, that fact that `https//snomed.info/id762705008` is modeled as a class and a property is expected and deliberate. This is an unusual situation so we reached out to some industry experts during the design of this change and we had confirmation that this is a legal thing to do. It was a few years back now but I believe this is known in OWL as "punning".

**Comment by fanavarro** [comment]
Hi @kaicode, and thanks for your quick answer. I heard about punning, but I though it was restricted to classes and individuals sharing the same URI. Nonetheless I was wrong since there are more types of punning, as I've just read at [https://www.w3.org/2007/OWL/wiki/Punning](https://www.w3.org/2007/OWL/wiki/Punning).
