### ISSUE TITLE
Error on running snomed-owl-toolkit

### ISSUE THREAD

**Issue by waydes** [IHTSDO/snomed-owl-toolkit#54]
Downloaded jar file and tried running classifier following the instructions:

D:\snowowl>java -Xms4g -jar snomed-owl-toolkit-3.0.3.jar -classify -rf2-snapshot-archives SnomedCT_InternationalRF2_PRODUCTION_20210131T120000Z.zip
no main manifest attribute, in snomed-owl-toolkit-3.0.3.jar

Wondering if there is an error on my part or problem with jar file?

**Comment by kaicode** [comment]
Please use `snomed-owl-toolkit-3.0.3-executable.jar`. The `snomed-owl-toolkit-3.0.3.jar` file is for use as a Java library.

**Comment by waydes** [comment]
OK, thanks.

Wayde Shipman, DVM, MS
Veterinary Medical Databases, President
Veterinary Medical Information Specialist, Virginia Tech
Oaks Veterinary Clinic, League City, Texas

Office - 281-332-9180 (preferred)
Cell - 832-444-5538
[image: ]

**Comment by waydes** [comment]
My oversight.  Thanks for pointing that out.

Wayde Shipman, DVM, MS
Veterinary Medical Databases, President
Veterinary Medical Information Specialist, Virginia Tech
Oaks Veterinary Clinic, League City, Texas

Office - 281-332-9180 (preferred)
Cell - 832-444-5538
[image: ]
