### ISSUE TITLE
Incorrect OWL expression conversion?

### ISSUE THREAD

**Issue by nagyo** [IHTSDO/snomed-owl-toolkit#56]
Hi,

We came across a concept definition and its corresponding axiom, where the OWL toolkit creates an interesting axiom conversion as a result.

In the SNOMED CT Canadian Extension the authors created a concept definition as follows:

[27841000087102 | Antigen of non-live Human alphaherpesvirus 3 (substance)](https://browser.ihtsdotools.org/?perspective=full&conceptId1=27841000087102&edition=MAIN/SNOMEDCT-CA/2021-09-30&release=&languages=en,fr
)

This concept is more general than the existing SNOMED International core concepts, hence they tried to "inject" this concept into the vaccine hierarchy as a super type to existing core concepts. Their first attempt was to add a SubClassOf OWL axiom to:

[844580005 | Antigen of inactivated whole Human alphaherpesvirus 3 (substance)](https://browser.ihtsdotools.org/?perspective=full&conceptId1=844580005&edition=MAIN/SNOMEDCT-CA/2021-09-30&release=&languages=en,fr)

`0199b0ce-50c0-cae8-b314-34c558501195	20200930	1	20621000087109	733073007	844580005	SubClassOf(:844580005 :27841000087102)`

But given that modifying core content is not advised, they inactivated the above member and created a GCI axiom in the latest 2021-09-30 release:

`3a6f0f27-adf8-50a6-af49-4488bf1884f7	20210930	1	20621000087109	733073007	27841000087102	SubClassOf(:844580005 :27841000087102)`

[The official SNOMED OWL Guide](https://confluence.ihtsdotools.org/display/DOCOWL/2.4.+Content+for+the+OWL+Axiom+Refset) does not cover whether the referenced component selection for this case was correct or not, because it has the following statements:

1. If an axiom is in the form of SubClassOf(C D) or EquivalentClasses(C D) where concept C is a precoordinated concept, the concept ID of C should be the referencedComponentId for this axiom.

2. If an axiom is in the form of SubClassOf(C D) where concept C is NOT a precoordinated concept and D is a precoordinated concept. This is a General Concept Inclusion (GCI) axiom. Because concept C is a sufficient but not necessary condition for concept D, the concept ID of D should be the referencedComponentId for this axiom.

3. If an axiom is in the form of SubClassOf(C D) or EquivalentClasses(C D) where both C and D are NOT precoordinated concepts, this is a GCI axiom and the referencedComponentId should be 733929006 |General concept inclusion axiom (metadata)|.

Case 1) was applicable for the old OWL axiom member, but not for the new GCI solution. Case 2) and 3) is also not applicable to this case because both concepts are precoordinated.

The reason why we are filing this issue here is because potentially there is a technical aspect of it. If someone wants to convert this OWL expression `27841000087102	SubClassOf(:844580005 :27841000087102)` with the OWL Toolkit, the result will be a normal class axiom instead of a GCI:

https://github.com/IHTSDO/snomed-owl-toolkit/blob/988cdc54fddb750424ffe21b4a2a1029412eb0bc/src/main/java/org/snomed/otf/owltoolkit/conversion/AxiomRelationshipConversionService.java#L153-L164

This axiom will then be converted into a normal class axiom again in Snowstorm:

https://github.com/IHTSDO/snowstorm/blob/d5f717a8f82d288c7a4253d05d4c185ff3b1d9c4/src/main/java/org/snomed/snowstorm/core/data/services/ConceptService.java#L473-L481

which will eventually lead to an incorrect representation in the official SNOMED CT Browser:

![image](https://user-images.githubusercontent.com/2010200/136792704-1c78a98a-d97c-4a64-8414-1ebffc99a7d4.png)

and an invalid SNOMED CT Concept diagram:

![image](https://user-images.githubusercontent.com/2010200/136793711-63d67aea-ec44-42a4-8cbf-30751cc9d21a.png)

because the OWL member is not represented as a GCI axiom in neither of the above.

We were able to find traces of a rule that an axiom is a GCI axiom only when the left hand side is an expression, i.e. there is at least an IS-A and another attribute, but we couldn't verify that with an official editorial guideline entry.

See here:
https://github.com/IHTSDO/snomed-drools-rules/blob/bf04075829cee4476a7670148d6f0dbac5d258bb/common-authoring/relationships/gci-axiom/GCIContainsParentAndAttribute.drl

and here:
https://github.com/IHTSDO/snomed-owl-toolkit/commit/9a234a9b40d96a5cc16901cd9a8e23ce96260598

Our questions are the following:

- shouldn't it be the responsibility of the toolkit to raise awareness of such axioms instead of silently converting them to normal class axioms?
- if it is rather the responsibility of third party implementers, then where can one find an official documentation about this rule regarding GCIs?

Any information regarding the topic is much appreciated!

Regards,

Gábor

**Comment by kaicode** [comment]
> if it is rather the responsibility of third party implementers, then where can one find an official documentation about this rule regarding GCIs?

The rules regarding the syntax of the OWL Axiom Refset can be found here: 
https://confluence.ihtsdotools.org/display/DOCOWL/2.4.+Content+for+the+OWL+Axiom+Refset#id-2.4.ContentfortheOWLAxiomRefset-ReferencedcomponentforanAxiom
`If an axiom is in the form of SubClassOf(C D) where concept C is NOT a precoordinated concept and D is a precoordinated concept. This is a General Concept Inclusion (GCI) axiom. Because concept C is a sufficient but not necessary condition for concept D, the ID of concept D should be the referencedComponentId for this axiom. Note, if C is a precoordinated concept, this SubclassOf axiom is NOT a GCI axiom and the concept D should not be assigned as the referencedComponentId.`
