### ISSUE TITLE
Classifying an extension

### ISSUE THREAD

**Issue by vigiso** [IHTSDO/snomed-owl-toolkit#58]
I need to classify the SNOMED CT Spanish extension by using the snomed-owl-toolkit. The Spanish extension comes with its own ZIP file and uses a RF2 file for the stated relationships (no OWL). Should I join the content of the international files with the content of the extension files? i.e.:

sct2_Concept_Snapshot_INT_20210131.txt + sct2_Concept_SpainExtensionSnapshot-es-ES_ES_20210601.txt
sct2_StatedRelationship_Snapshot_INT_20210131.txt + sct2_StatedRelationship_SpainExtensionSnapshot-es-ES_ES_20210601.txt

and after storing the resulting files into the international ZIP, execute the classification process?

Thanks!

**Comment by kaicode** [comment]
Hi @vigiso, thanks for reaching out.

All extensions since July 2019 should have an OWL file. This sounds like the Spanish national extension, not the Spanish Edition which does have an OWL file.

The snomed-owl-toolkit can correctly classify using a mixture of OWL axioms and stated relationships but only if none of the stated relationships use an international concept as the sourceId.
If this is the case you should be able to classify by listing both RF2 archives, comma separated, after the `-rf2-snapshot-archives` parameter. 

Something like this:
```
java -Xms4g -jar snomed-owl-toolkit*executable.jar -classify -rf2-snapshot-archives SnomedCT_InternationalRF2_PRODUCTION_20210130T120000Z.zip,SnomedCT_SpainExtension-es_PRODUCTION_20210601.zip
```
I have guessed the Spain extension filename so please correct it.

I hope that helps.

Kind regards,
Kai Kewley

**Comment by vigiso** [comment]
Hi @kaicode, thanks for your answer.

Unfortunately,  some stated relationships of the Spanish National System (SNS) extension use an international concept as the sourceId. I'm trying to convert its stated relationships RF2 file into an OWL file by using:

```
java -Xms4g -jar snomed-owl-toolkit-3.0.3-executable.jar -rf2-to-owl -rf2-snapshot-archives SnomedCT_Extension_Española_SNS.zip
```

But I obtain the following error:

```
java.lang.IllegalArgumentException: malformed input off : 76, length : 1
        at java.base/java.lang.StringCoding.throwMalformed(StringCoding.java:698)
        at java.base/java.lang.StringCoding.decodeUTF8_0(StringCoding.java:885)
        at java.base/java.lang.StringCoding.newStringUTF8NoRepl(StringCoding.java:978)
        at java.base/java.lang.System$2.newStringUTF8NoRepl(System.java:2270)
        at java.base/java.util.zip.ZipCoder$UTF8.toString(ZipCoder.java:60)
        at java.base/java.util.zip.ZipCoder.toString(ZipCoder.java:87)
        at java.base/java.util.zip.ZipInputStream.readLOC(ZipInputStream.java:302)
        at java.base/java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:124)
        at org.ihtsdo.otf.snomedboot.ReleaseImporter.unzipRelease(ReleaseImporter.java:126)
        at org.ihtsdo.otf.snomedboot.ReleaseImporter.loadEffectiveSnapshotReleaseFileStreams(ReleaseImporter.java:83)
        at org.snomed.otf.owltoolkit.taxonomy.SnomedTaxonomyBuilder.build(SnomedTaxonomyBuilder.java:121)
        at org.snomed.otf.owltoolkit.taxonomy.SnomedTaxonomyBuilder.build(SnomedTaxonomyBuilder.java:82)
        at org.snomed.otf.owltoolkit.conversion.RF2ToOWLService.convertRF2ArchiveToOWL(RF2ToOWLService.java:45)
        at org.snomed.otf.owltoolkit.Application.rf2ToOwl(Application.java:145)
        at org.snomed.otf.owltoolkit.Application.run(Application.java:88)
        at org.snomed.otf.owltoolkit.Application.main(Application.java:53)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.nio.charset.MalformedInputException: Input length = 1
```

Any idea about what's happening?

Thank you,
Vicent

**Comment by kaicode** [comment]
Sorry to hear you are having trouble processing the Spanish National System RF2 archive.
The [line of code throwing the exception](https://github.com/IHTSDO/snomed-boot/blob/3.0.0/src/main/java/org/ihtsdo/otf/snomedboot/ReleaseImporter.java#L126) is just trying to read the next entry in the zip file. A low level encoding error is thrown. 

It looks like the archive may be corrupted or maybe it is not encoded using UTF-8? Our tooling only supports UTF-8 encoding because that is part of the SNOMED CT RF2 standard specification.

Things you could try:
- Download the RF2 archive again in case it was corrupted in transfer.
- Check the RF2 archive MD5 checksum if one is available from the source website?
- Try to find out what encoding the RF2 archive uses - I'm not sure how to do that, you could search for a solution.
- Try extracting the archive then recreating it using UTF-8 encoding.

I hope that helps!

**Comment by vigiso** [comment]
Hi @kaicode,

Finally, the problem is that the ZIP file contains two PDF files with some documentation. After deleting such files I have finally generated the .owl file. Can you tell me the next steps to perform the classification of the extension? Should I delete the stated relationships RF2 file (which contains some international concepts as sourceIds) from the ZIP, and extract the axioms from the OWL file?

Thank you!

Vicent

**Comment by kaicode** [comment]
I'm glad you are able to run the OWL conversion. That shows that the archive can be read by the toolkit. The `-rf2-to-owl` function produces an OWL file for use in external applications like Protégé, however file can not be used for classification by the toolkit.

To run the classification function please use the `-classify` flag instead. 
Please note that although this function can take a mixture of axioms and stated relationships as input the stated relationships should not have the same sourceId as concepts that already have axioms. If there are stated relationships with a sourceId of an International concept they may be merged into the International axioms in unpredictable ways. The maintainer of the extension should really be the party to convert those stated relationships to axioms and to review the effect on classification. This is a modelling activity so we should not rely on automatic processes to get this correct.

The classification function will create the ontology by loading both the axioms and stated relationships to produce an ontology and classify that. 

The output will be an RF2-like archive with a delta of inferred relationship changes relative to the existing inferred relationships in the input snapshot. If the output archive has no rows (only the header line) then the input was already classified correctly and the existing inferred relationship snapshot contains an up to date set of relationships. If you would like a complete set of inferred relationships as output then remove the inferred relationships from the input. The relationships in the output file have no relationship identifiers in the first column because SCTID generation is not within scope of this tool.

I hope that helps!

**Comment by vigiso** [comment]
Hello Kai, thank you for your answer :)

I have extracted the axioms from the OWL file that the toolkit produces and created a new axioms file for my extension (with the same header as the International OWL file). I have two questions/doubts:

1. Extracting the axioms from the OWL file generated by the toolkit is a correct way to obtain an OWL file to represent the stated relationships of my extension?

2. Is this new axioms file able to be used to classify? Or the problem with the sourceIds that are International concepts persists?

Thanks!

**Comment by vigiso** [comment]
Thanks kaicode for your answer. 

Regarding the inferred relationships file of the international edition, do you know what is the policy for assigning id's to each of the inferred relationships? I wonder if I will need to create id's for the inferred relationships obtained after the classification of my extension. 

Thanks!

**Comment by kaicode** [comment]
Yes, inferred relationships should have identifiers. A prerequisite to creating SCTID identifiers is registering for a namespace.
Here is a page from the Extensions Practical Guide that explains what a namespace is and has a link to the application form.
https://confluence.ihtsdotools.org/display/DOCEXTPG/4.1+Namespaces

**Comment by vigiso** [comment]
Hello again, Kai

I would like to know if there exists documentation about the criteria used to set the group numbers to the inferred relationships. 

I hope you can help me.

Thanks :)

**Comment by kaicode** [comment]
Hi @vigiso, there is no documentation on this that I know of. Group numbers have no meaning, they are just to separate groups of relationships. The classification process starts with a set of relationships and relationship groups from deserialising the axioms of a concept, and those inherited by inferred parents. Then the normalisation process boils down this set by checking which relationships and groups subsume each other - only the most specific sets are kept. If the concept is new then the groups are just numbered sequentially starting with 1. We try to minimise the set of changed relationships for existing concepts by attempting to reuse existing relationships and group numbers.
I hope that helps. Let me know if you have further questions.

**Comment by vigiso** [comment]
Hi @kaicode. I have some concepts that are present in both **sct2_Concept_SpainExtensionSnapshot** and **sct2_sRefset_OWLExpression_SpainExtensionSnapshot** files, but after classification there is no any inferred relationship for them. Is it possible?
Thanks :)

**Comment by kaicode** [comment]
The result of the classification process are inferred relationship changes. If there are inferred relationships for a concept being provided in the input and the classification process finds that no changes are needed to the inferred relationships of that concept then there will be no inferred relationship changes in the output for that concept. Does that help?

**Comment by vigiso** [comment]
As input for the classification process I provide the International Edition zip and a zip that only includes sct2_Concept_SpainExtensionSnapshot and sct2_sRefset_OWLExpression_SpainExtensionSnapshot files, so no inferred relationships for the extension are provided. Thanks.

**Comment by kaicode** [comment]
I sounds like the axiom for the concept you mentioned has a problem. You should get at least an inferred "is a" relationship for all concepts. I wonder if it has a syntax issue, has an unexpected format or refers to a concept that is inactive or does not exist. 

You could check for errors or warnings in the logs, around the time when axiom loading/parsing is mentioned.

You could try [generating an OWL file](https://github.com/IHTSDO/snomed-owl-toolkit#snomed-rf2-to-owl-file-conversion) from the same input files. This OWL file could be opened in Protégé to check that everything looks as expected. The ELK OWL reasoner can also be run in Protégé to check what parents are inferred.

**Comment by vigiso** [comment]
Thank you @kaicode.

In the context of the extension, when I generate the .owl file from the stated relationships file by using the tool, it is created a "Classes" section, but also an "Object properties" section. Then, I generate the sct2_sRefset_OWLExpression_SpainExtensionSnapshot file by extracting the axioms from the .owl file. For the "Classes" section, it is created a "SubClassOf" for the "is a" relationship. For the "Object properties" section, it is created a "SubObjectPropertyOf" for the "is a" relationship. I have found that for the "SubObjectPropertyOf" it is not generated an inferred relationship. So, I have replaced each "SubObjectPropertyOf" by a "SubClassOf" in the sct2_sRefset_OWLExpression_SpainExtensionSnapshot file and now the classification process generates inferred relationships for such concepts.

Is it correct?

Thank you.

**Comment by kaicode** [comment]
Attribute concepts must use a`SubObjectPropertyOf` axiom.

Here are two axioms for attribute concepts from the International Edition, `363698007 |Finding site (attribute)|` and `762949000 |Has precise active ingredient (attribute)|`:
```
id	effectiveTime	active	moduleId	refsetId	referencedComponentId	owlExpression
ad197712-839b-4c11-94c0-0fb9f557421d	20190731	1	900000000000012004	733073007	363698007	SubObjectPropertyOf(:363698007 :762705008)
2d87e670-54ba-4463-83be-1e7e1e972fa6	20190731	1	900000000000012004	733073007	762949000	SubObjectPropertyOf(:762949000 :127489000)
```

The following inferred is-a relationships are generated for those:
```
id	effectiveTime	active	moduleId	sourceId	destinationId	relationshipGroup	typeId	characteristicTypeId	modifierId
9059400024	20180131	1	900000000000012004	363698007	762705008	0	116680003	900000000000011006	900000000000451002
9068210024	20180131	1	900000000000012004	762949000	127489000	0	116680003	900000000000011006	900000000000451002
```

It is a little unusual for an extension to add an attribute concept but it should work as above.

**Comment by kaicode** [comment]
Hi @vigiso. Thanks for sharing the axioms, that helps. 

This toolkit expects attribute concepts to have only one axiom and one parent. The parent must be `762705008 |Concept model object attribute (attribute)|` or one of its descendants. 

We used to use the `410662002 |Concept model attribute (attribute)|` concept but since the introduction of concrete domains and the `762706009 |Concept model data attribute (attribute)|` concept, now normal attributes must be a descendant of `762705008 |Concept model object attribute (attribute)|`.

If you would like to organise your attributes using `13111000122102 |attribute of the conceptual model for SNOMED CT National Extension for Spain (attribute)|` you could make that a descendant of `762705008 |Concept model object attribute (attribute)|` then update all your other attributes to keep this as a parent but to remove the other axiom.

For example, the axioms to represent 13111000122102 and 21931000122103 would be:
```
id	effectiveTime	active	moduleId	refsetId	referencedComponentId	owlExpression
a61d4cce-c974-48aa-a55b-c27017be931f	20221201	1	900000001000122104	733073007	13111000122102	SubClassOf(:13111000122102 :762705008)
33a09508-b76c-4dc8-918c-504fb939178d	20221201	1	900000001000122104	733073007	21931000122103	SubObjectPropertyOf(:21931000122103 :13111000122102)

```

I hope that helps.

**Comment by vigiso** [comment]
Hi @kaicode. Thanks, that helped :)

- Another doubt that I have is about the inferred relationships obtained after classifying the extension. Some inferred relatioships are obtained for some concepts of the International Edition. I supose it should be correct?

- And a second doubt that I have is about the SNOMED CT browser. Since the International Edition RF2 release doesn't include active stated relationships anymore, I would like to know how axioms are showed as relationships on both Details and Diagram tabs. May be the owl-to-stated tool is being used?

Thank you!

**Comment by vigiso** [comment]
Hi @kaicode,
Thanks for your last answer.

After the classification process, it is obtained a relationships file with active rows for new inferences and inactive rows for redundant relationships. Is it correct to obtain inside of this file inactivations of relationships of the International Edition? Is it correct to include these International edition inactivated relationships inside of an extension, where they have never been previously activated? 

Thanks again.

**Comment by kaicode** [comment]
Hi @vigiso,
Yes the classification process may make some International relationships inactive when classifying an extension. It should only do this for relationships that are active in the version of the International edition that you are classifying against. Yes you should include those relationships as inactive in your extension and it's important that you use your extension module for these inactive rows, even though they are International relationships. This is common practise.

Does that answer your question?

**Comment by vigiso** [comment]
Hi @kaicode,
Yes. Thanks a lot!

**Comment by vigiso** [comment]
Hello again, @kaicode,

I have a doubt about GCIs: I know that GCIs are part of the "Refset_OWLExpression" file. The question is how can I differentiate them from the others. It seems that their OWL expression starts with "SubClassOf(ObjectIntersectionOf(". Is this correct and enough to differentiate them from the rest?

Thanks.

**Comment by kaicode** [comment]
Hi @vigiso,
Yes, finding OWL expressions that start with that string would identify all recognised GCIs.
In the 2023-01-31 International Edition it looks like there are 329 active and 53 inactive expressions that match. These are the GCIs.

**Comment by vigiso** [comment]
Okay, thank you :)

**Comment by vigiso** [comment]
Hello again, @kaicode,

I have a new question regarding GCIs. I see that you are showing the GCI OWL expressions in tabular form in the SNOMED CT browser for each concept. I know that the OWL tool is capable of converting OWL expressions into stated relationships, which is a solution to show OWL expressions in tabular form. However, I have tried this conversion and it seems that GCI OWL expressions are not converted into stated relationships, only "regular" OWL expressions are converted. 

So I don't know how to convert GCI OWL expressions into stated relationships to show its content in tabular form and without losing the information that they are GCI and not "regular" in order to differentiate them in the tabular representation.

I hope you can help me.

Thanks!

**Comment by kaicode** [comment]
The Snowstorm terminology server uses the SNOMED OWL Toolkit as a java library to convert axiom expressions to a java object that has a definition status and a left and right side, each with either a named concept or set of relationships and groups.
The java method is here: https://github.com/IHTSDO/snomed-owl-toolkit/blob/master/src/main/java/org/snomed/otf/owltoolkit/conversion/AxiomRelationshipConversionService.java#L55

The OWL Axiom to stated relationship function that exists within the toolkit has very limited use cases like some types of validation processes. 
Converting axioms to stated relationships loses information. In the stated relationship file there is no way to express: 
- multiple axioms for a single concept
- GCI axioms
- Property chains
- Attribute behaviours like transitive, reflexive
As you said, only normal axioms can be converted to stated relationships, and even then if a concept has two axioms then the stated relationships will be a mess.

If you let me know what you are trying to achieve I may be able to suggest an alternative solution.

**Comment by vigiso** [comment]
Hello again, @kaicode,

Thank you for your last answer. It was useful to me.

Now I have another problem while classifying the Spanish extension. The problem is that the inferred relationships file obtained after classifying the extension includes some attributes that don't accomplish the MRCM grouping rules. Concretely:

- _726542003 |Has disposition (attribute)|_: is grouped in some cases
- _766939001 |Plays role (attribute)|_: is grouped in some cases
- _127489000 |Has active ingredient (attribute)|_: is ungrouped in some cases

It should be noted that I receive a stated relationships file and after including the MRCM files (from the International edition) inside the zip, I convert it into an OWL refset file using the snomed-owl-toolkit-3.0.6-executable.jar (-rf2-stated-to-complete-owl), and then I classify the extension (-classify).

I don't know where is the problem. The stated rels file that I receive is correct in terms of MRCM attribute grouping rules, and the MRCM files are included in the process of -rf2-stated-to-complete-owl and also in the -classify process.

I hope you can help me.

Thanks :)

**Comment by vigiso** [comment]
Hi @kaicode,

Thank you for your quick and detailed response. Let me show you an example from the Spanish extension:

**Concept:** 
_37421000122104 |COVID-19 vaccine with inactivated SARS-CoV-2 antigen [Sinovac] (medicinal product)|_

**Stated rels:**
_2079011000122124	20210601	1	900000001000122104	37421000122104	318331000221102	0	766939001	900000000000010007	900000000000451002
2083671000122126	20220601	1	900000001000122104	37421000122104	1153537004	1	127489000	900000000000010007	900000000000451002_ 

**Output lines after the -rf2-stated-to-complete-owl process for the ungrouped attributes (using der2_cissccRefset_MRCMAttributeDomainSnapshot_INT_20230131.txt):**
_Using never grouped role list from MRCM reference set [1230370004, 733933004, 733931002, 733932009, 733928003, 774081006, 733930001]_

**Axiom obtained:**
_64e61bf1-484f-4ef9-a488-97a4ec55a494	20231201	1	900000001000122104	733073007	37421000122104	SubClassOf(:37421000122104 ObjectIntersectionOf(:28531000087107 :66571000122107 ObjectSomeValuesFrom(:609096000 ObjectSomeValuesFrom(:127489000 :1153537004)) ObjectSomeValuesFrom(:609096000 ObjectSomeValuesFrom(:766939001 :318331000221102))))_

**Inferred rels obtained after classifying:**
_204601000122126	20221201	1	900000001000122104	37421000122104	318331000221102	1	766939001	900000000000011006	900000000000451002
218831000122128	20231201	1	900000001000122104	37421000122104	1153537004	2	127489000	900000000000011006	900000000000451002_

The error that has been reported to me regarding this example is that the attribute 766939001 |Plays role (attribute)| should not be grouped. However, this attribute is not in the list of ungrouped attributes obtained from the -rf2-stated-to-complete-owl process althoug it is in the der2_cissccRefset_MRCMAttributeDomainSnapshot_INT_20230131.txt file with "grouped" set to 0:

_4143563b-44f1-4a90-99be-e05dea540b7b	20180731	1	900000000000012004	723561005	766939001	373873005	0	0..*	0..0	723597001	723596005_

I also have a question here: when "grouped" is set to 0 means that the attribute should not be grouped and when it is set to 1 means that it is mandatory for the attribute to be grouped or that it is only possible to group it?

Thanks again.

**Comment by kaicode** [comment]
When the MRCM has grouped=0 (false) that means it can not be in a group. When grouped=1 (true) that means it must always be in a group. These rules are not optional. The MRCM does not describe when attributes are self-grouped.

In the stated relationship file the use of group number "0" was overloaded. This was used for 
- A) relationships that were not grouped, for example the is-a relationships
- B) and attributes that were not grouped
- but also group 0 was used for C) a small set of attribute that were "self grouped", i.e. relationships that should be put into a group on their own when converted to an axiom

The MRCM is used to identify attributes in B that are never grouped. The remainder are assumed to be C, self-grouped.

Your output snippet contains:
```
Using never grouped role list from MRCM reference set [1230370004, 733933004, 733931002, 733932009, 733928003, 774081006, 733930001]
```

However when I run the conversion process using the Jan 2023 International Edition I get this:
```
java -jar target/snomed-owl-toolkit-3.0.10-executable.jar -rf2-stated-to-complete-owl -rf2-snapshot-archives ../../release/SnomedCT_InternationalRF2_PRODUCTION_20230131T120000Z.zip
....
2023-06-21 15:27:44,120 [INFO  ] [main] org.snomed.otf.owltoolkit.taxonomy.SnomedTaxonomy - Using never grouped role list from MRCM reference set [1230370004, 733931002, 736476002, 736473005, 272741003, 774081006, 766939001, 774158006, 736518005, 1148793005, 1148969005, 733932009, 840560000, 1142141006, 860781008, 736475003, 836358009, 411116001, 1149367008, 1148967007, 736472000, 827081001, 1142139005, 733930001, 736474004, 320091000221107, 1142143009, 733933004, 1142140007, 1148965004, 1148968002, 763032000, 726542003, 733928003, 774159003, 738774007]
```
This list of 35 ungrouped attributes matches what I can see in the Jan 2023 MRCM Attribute Domain snapshot and includes the `766939001 |Plays role (attribute)|` as you mentioned it should. I think the tool is not getting the correct information from the MRCM. Perhaps there are multiple MRCM files in the snapshot archives you are loading and it's picking the wrong one?

**Comment by vigiso** [comment]
Hello, @kaicode 

Thank you for our answer. This is the execution line I am using:

`java --add-opens java.base/java.lang=ALL-UNNAMED -Xms2g -jar snomed-owl-toolkit-3.0.6-executable.jar -rf2-stated-to-complete-owl -rf2-snapshot-archives SNSForOWL.zip`

The content of `SNSForOWL.zip` file is the following:

```
der2_cissccRefset_MRCMAttributeDomainSnapshot_INT_20230131.txt
sct2_Concept_SpainExtensionSnapshot_ES_20231201.txt
sct2_StatedRelationship_SpainExtensionSnapshot_ES_20231201.txt
sct2_Relationship_SpainExtensionSnapshot_es_ES_20231201.txt (empty, but it is mandatory to add it since otherwise the process ends in error)
```

If you want to try to execute the process, you can find the zip here:
https://drive.google.com/file/d/1Wyf6uaPrTX0jQvVkmbEVokDsOBjOMQBW/view?usp=sharing

It would be useful for me since may be I am doing something wrong.

Thanks.

**Comment by kaicode** [comment]
I would recommend taking the MRCM file out of the SNSForOWL zip and passing in a second zip file that is the International Edition, like this:
```
java --add-opens java.base/java.lang=ALL-UNNAMED -Xms2g -jar snomed-owl-toolkit-3.0.6-executable.jar -rf2-stated-to-complete-owl -rf2-snapshot-archives SNSForOWL.zip,SnomedCT_InternationalRF2_PRODUCTION_20230131T120000Z.zip
```
That way the MRCM will be taken from the International Edition. The toolkit may need the rest of the SNOMED CT hierarchy from the international edition to work properly.
