### ISSUE TITLE
Maven repository unreachable

### ISSUE THREAD

**Issue by rwynne** [IHTSDO/snomed-owl-toolkit#59]
I'm experiencing a build failure for the latest version 3.0.5. 
Our local Nexus repository points to https://maven.ihtsdotools.org/content/repositories/releases/ 
though the site is currently unreachable.

Specifically, during build we are unable to resolve the latest snomed-boot-3.0.0.jar dependency.
I've found the download for the 3.0.3 toolkit executable jar asset in the interim.

**Comment by rwynne** [comment]
Sent an inquiry to info@snomed.org and received a response from @rorydavidson to use https://nexus3.ihtsdotools.org/
We have updated our Nexus proxies here at NLM and builds are working as they should.

**Comment by kaicode** [comment]
Looks like the repositories are correctly configured in the [3.0.5 pom](https://github.com/IHTSDO/snomed-owl-toolkit/blob/3.0.5/pom.xml#L161) file so nothing further to do. Glad you got your build sorted 👍 .
