### ISSUE TITLE
Include Refsets in OWL file

### ISSUE THREAD

**Issue by Marvjowa** [IHTSDO/snomed-owl-toolkit#65]
Hello!

I'm new to much of this, so I'm sorry in advance if this question has a very obvious answer.

I managed to create an OWL-file from SnomedCT, but realised afterwards that the "Simple Map Refset name"s are not included, e.g. the ones found [in the SNOMED Browser](https://browser.ihtsdotools.org/?perspective=full&conceptId1=770401007&edition=MAIN/2022-03-31&release=&languages=en) under "Refsets" on the right, such as "SNOMED CT to ICD-10 extended map".
Is there a way to include these in the created OWL-file?

Thank you in advance!

**Comment by kaicode** [comment]
Hi there! Thanks for reaching out.

The concepts/classes that represent these refsets should be in the generated OWL file but you are right that the members of these maps are not. The SNOMED RF2 distribution contains a map to the identifiers of the ICD-10 codes but no modelling / axioms for ICD-10. 

Is there a standard way to represent such a map in OWL format?

**Comment by Marvjowa** [comment]
Hello! I'm very sorry for the late reply.
The ICD-10 were just one example, the "CTV3 to SNOMED CT simple map" would be another from the link above.
I'm new to OWL so I am unsure whether there is a standard way, but do I understand you correctly, that it would be possible to include the maps in the OWL file if a fitting representation could be found?

**Comment by kaicode** [comment]
We are open to enhancing the OWL ontology generated by this tool provided that the enhancements are useful to many and aligned with best practice.
I wondered if annotations could be used to provide the URI to a concept from an alternate classification but I haven't been able to find any examples of that. The ICD-10 codes have URIs that are used in FHIR.
