### ISSUE TITLE
Relationship modifier

### ISSUE THREAD

**Issue by obali** [IHTSDO/snomed-owl-toolkit#7]
The toolkit don't seem to cater for the following constraint:

- OWLObjectAllValuesFrom (universal restriction)

So extensions that are using both values for the modifier ID can not utilise the toolkit.

**Comment by kaicode** [comment]
Hi Orsi, thank you for your suggestion. 
Unfortunately this feature is not the Snomed International roadmap at this time.
Please feel free to fork the project to add additional DL support for specific extensions in your owl version.
The Modelling Advisory Group govern the DL feature set within this official Snomed OWL toolkit repository but we would very much welcome contributions if they are in line with what has been agreed.
Please get in touch if you have any further questions.
Kind regards.

**Comment by kaicode** [comment]
Hi Orsi,
I've gathered some more feedback about your requests.

Universal restriction is not included in the SNOMED CT Logic Profile following the recommendation from the Modelling Advisory Group. 
Feel free to contact the group for more information. The contact people are Peter Williams and Yongsheng Gao.
