### ISSUE TITLE
range and domain

### ISSUE THREAD

**Issue by dinani65** [IHTSDO/snomed-owl-toolkit#77]
Hello,
After transformation of SNOMED CT RF2 into .owl via snomed-owl-toolkit, I used protege to export the file in .ttl.
I am trying to write a SPARQL query to find e.g., a property with a specific domain and range. While with the current structure of 
 snomed ct, I am not able to query it.
 
 Could you pls give me some hints regarding how to extract my information needs across snomed ct?
 For example. I was expecting to find get result for a query like:
 `
SELECT distinct ?property 
WHERE {
  ?property rdf:type owl:ObjectProperty .
  ?property rdfs:domain ex:116154003.
  ?property rdfs:range ex:64572001.

}
`

**Comment by kaicode** [comment]
I don't have any experience with SPARQL, I'm not sure if someone else in the community can help here.

What is it you are trying to find out? Perhaps I can suggest an [ECL query](http://snomed.org/ecl) to help.
