### ISSUE TITLE
No Stated Relationships or Axioms were found.

### ISSUE THREAD

**Issue by Huido2000** [IHTSDO/snomed-owl-toolkit#78]
Hi Kaicode!

I am trying to transform the the Spanish version -- SnomedCT_Spanish_Edition.zip -- with the -- snomed-owl-toolkit-3.0.6-executable.jar -- and I receive the following message " org.snomed.otf.owltoolkit.conversion.ConversionException: No Stated Relationships or Axioms were found. An Ontology file can not be produced."

Do you know where can be the problem? 

Thanks in advance!

**Comment by CoderMChu** [comment]
@Huido2000 The error message suggests that it can't find any stated relationship or axiom files in the edition package.

OWL toolkit expects these two snapshot files:

sct2_StatedRelationship_Snapshot_*.txt
sct2_sRefset_OWLExpressionSnapshot_*.txt

You can check these files in the unzipped older or use "unzip -v SnomedCT_Spanish_Edition.zip" to list all files.

**Comment by Huido2000** [comment]
Thanks for the quick answer @CoderMChu !

As you can see in the list below, both files are contained there;

 SnomedCT_SpanishRelease-es_PRODUCTION_20221031T120000Z
        Full
            Refset
                Content
                    der2_cRefset_AssociationSpanishExtensionFull_INT_20221031.txt
                    der2_cRefset_AttributeValueSpanishExtensionFull_INT_20221031.txt
                    der2_Refset_SimpleSpanishExtensionFull_INT_20221031.txt
                Language
                    der2_cRefset_LanguageSpanishExtensionFull-es_INT_20221031.txt
                Map
                    der2_iisssccRefset_ExtendedMapSpanishExtensionFull_INT_20221031.txt
                    der2_sRefset_SimpleMapSpanishExtensionFull_INT_20221031.txt
                Metadata
                    der2_cciRefset_RefsetDescriptorSpanishExtensionFull_INT_20221031.txt
                    der2_ssRefset_ModuleDependencySpanishExtensionFull_INT_20221031.txt
                    der2_ciRefset_DescriptionTypeSpanishExtensionFull_INT_20221031.txt
                    der2_cissccRefset_MRCMAttributeDomainSpanishExtensionFull_INT_20221031.txt
                    der2_cRefset_MRCMModuleScopeSpanishExtensionFull_INT_20221031.txt
                    der2_ssccRefset_MRCMAttributeRangeSpanishExtensionFull_INT_20221031.txt
                    der2_sssssssRefset_MRCMDomainSpanishExtensionFull_INT_20221031.txt
            Terminology
                sct2_Concept_SpanishExtensionFull_INT_20221031.txt
                sct2_Description_SpanishExtensionFull-es_INT_20221031.txt
                sct2_Relationship_SpanishExtensionFull_INT_20221031.txt
                sct2_RelationshipConcreteValues_SpanishExtensionFull_INT_20221031.txt
                sct2_StatedRelationship_SpanishExtensionFull_INT_20221031.txt
                sct2_TextDefinition_SpanishExtensionFull-es_INT_20221031.txt
                sct2_Identifier_SpanishExtensionFull_INT_20221031.txt
                sct2_sRefset_OWLExpressionSpanishExtensionFull_INT_20221031.txt
        Snapshot
            Refset
                Content
                    der2_cRefset_AssociationSpanishExtensionSnapshot_INT_20221031.txt
                    der2_cRefset_AttributeValueSpanishExtensionSnapshot_INT_20221031.txt
                    der2_Refset_SimpleSpanishExtensionSnapshot_INT_20221031.txt
                Language
                    der2_cRefset_LanguageSpanishExtensionSnapshot-es_INT_20221031.txt
                Map
                    der2_iisssccRefset_ExtendedMapSpanishExtensionSnapshot_INT_20221031.txt
                    der2_sRefset_SimpleMapSpanishExtensionSnapshot_INT_20221031.txt
                Metadata
                    der2_cciRefset_RefsetDescriptorSpanishExtensionSnapshot_INT_20221031.txt
                    der2_ssRefset_ModuleDependencySpanishExtensionSnapshot_INT_20221031.txt
                    der2_ciRefset_DescriptionTypeSpanishExtensionSnapshot_INT_20221031.txt
                    der2_cissccRefset_MRCMAttributeDomainSpanishExtensionSnapshot_INT_20221031.txt
                    der2_cRefset_MRCMModuleScopeSpanishExtensionSnapshot_INT_20221031.txt
                    der2_ssccRefset_MRCMAttributeRangeSpanishExtensionSnapshot_INT_20221031.txt
                    der2_sssssssRefset_MRCMDomainSpanishExtensionSnapshot_INT_20221031.txt
            Terminology
                sct2_Concept_SpanishExtensionSnapshot_INT_20221031.txt
                sct2_Description_SpanishExtensionSnapshot-es_INT_20221031.txt
                sct2_Relationship_SpanishExtensionSnapshot_INT_20221031.txt
                sct2_RelationshipConcreteValues_SpanishExtensionSnapshot_INT_20221031.txt
                sct2_StatedRelationship_SpanishExtensionSnapshot_INT_20221031.txt
                sct2_TextDefinition_SpanishExtensionSnapshot-es_INT_20221031.txt
                sct2_Identifier_SpanishExtensionSnapshot_INT_20221031.txt
                sct2_sRefset_OWLExpressionSpanishExtensionSnapshot_INT_20221031.txt
        Readme_es_20221031.txt
        release_package_information.json

So I don't find where the mistake is.

**Comment by CoderMChu** [comment]
@Huido2000 That's strange. I have just tested this locally using 3.0.6 with following command and it has worked for me.
`java -Xms4g -jar target/snomed-owl-toolkit*executable.jar -rf2-to-owl -rf2-snapshot-archives /snomed-releases/SnomedCT_SpanishRelease-es_PRODUCTION_20221031T120000Z.zip`

**Comment by CoderMChu** [comment]
@Huido2000  Please use full path after -rf2-snapshot-archives. Also you can use multiple zip files separated by comma.
e.g:
`java -Xms4g -jar target/snomed-owl-toolkit*executable.jar -rf2-to-owl -rf2-snapshot-archives /snomed-releases/SnomedCT_InternationalRF2_PRODUCTION_20220731T120000Z.zip,snomed-releases/SnomedCT_SpanishRelease-es_PRODUCTION_20221031T120000Z.zip`

**Comment by CoderMChu** [comment]
@Huido2000 Unfortunately that is caused by your computer doesn't have enough RAM. You could try 1g for SnomedCT_SpanishRelease-es_PRODUCTION_20221031T120000Z.zip file only. It seems to be working for me locally.
