### ISSUE TITLE
Incorrect creation of acceptable and prefered synonym

### ISSUE THREAD

**Issue by legallm** [IHTSDO/snomed-owl-toolkit#79]
Hello @kaicode,

It seems to have an issue in the writing process of the acceptable and preferred synonym in the addDescriptionAnnotations function of [OntologyService.java](https://github.com/IHTSDO/snomed-owl-toolkit/blob/master/src/main/java/org/snomed/otf/owltoolkit/ontology/OntologyService.java).

In the case of a concept with a description preferred in en-US and acceptable in en-GB, the annotation concerning the acceptable synonym will not be created because of the way the if-else block is written.

For example, the concept 312413002 use two synonyms, one with "categorized" and one with "categorised". The RF2 file shows that the "categorized" synonym is Preferred in en-US but Acceptable in en-GB, the "categorised" synonym is Preferred in en-GB but Acceptable in en-US. However, the tool produces an OWL file containing only the Preferred acceptability of those synonyms.

Thank you by advance!

**Comment by kaicode** [comment]
Hi @legallm

It's true. The current behaviour limits the number of times the same description will be written into the OWL file. It can generally be assumed that terms that are preferred in en-us are acceptable in en-gb, and that terms preferred in en-gb are acceptable in en-us. 
Is this causing problems for you?

**Comment by legallm** [comment]
Hi, we just ran some tests as we are planning to use the converter and noticed the mentioned difference. If it is intentional to limit the number of description, there is no problem.

Thank you for your answer!

**Comment by kaicode** [comment]
Thanks for letting us know! 👍
