### ISSUE TITLE
Concrete domain support?

### ISSUE THREAD

**Issue by obali** [IHTSDO/snomed-owl-toolkit#8]
It seems like there is no support for concrete domains, although it is used in a number of SNOMED CT extensions.

Please see this RF2 snippet from the SG extension as an example:

```
id	effectiveTime	active	moduleId	refsetId	referencedComponentId	uomId	operatorId	attributeName	dataValue	characteristicTypeId
8ff7f118-a423-4db8-b2c7-0fdcd3a18b27	20150519	1	195941000132101	20021000132103	73827721000133107		276136004	doseFormTradeSynonym	Jelly	900000000000227009
```

Feel free to reach out if you need more examples or information! Thank you!

**Comment by kaicode** [comment]
Hi Orsi, thank you for your suggestion. 
Unfortunately this feature is not the Snomed International roadmap at this time.
Please feel free to fork the project to add additional DL support for specific extensions in your owl version.
The Modelling Advisory Group govern the DL feature set within this official Snomed OWL toolkit repository but we would very much welcome contributions if they are in line with what has been agreed.
Please get in touch if you have any further questions.
Kind regards.

**Comment by kaicode** [comment]
Hi Orsi,
I've gathered some more feedback about your requests.

> We definitely welcome contributions for concrete domains. We are going to finalise the SNOMED CT Logic Profile Specification for the July 2018 release. It would be very helpful if B2i can provide information on what datatypes are required for supporting national extensions. So, we can consider to include those datatypes in the profile. 

I've emailed you the relevant working documents.

Kind regards,
Kai

**Comment by kaicode** [comment]
We will talk about the initial plans for concrete domains in the official SNOMED CT DL profile in the Modeling Advisory Group meetings next week at the April conference.

**Comment by kaicode** [comment]
Concrete domain support will be implemented by the end of this year (2020) to support the International Edition concrete domains technical preview which is due Q1 2021.

**Comment by waydes** [comment]
In order to classify correctly will the reasoner require concrete values in the OWL format or can the concrete values be the same format as in the release files?  Is concrete domain support implemented at this time?

**Comment by kaicode** [comment]
Hi @waydes, yes concrete domain support was implemented to produce the [Concrete Domains Technical Preview](https://www.snomed.org/news-and-events/articles/snomed-delivers-technical-preview-concrete-domains), further technical information is available via that page.

Yes the stated concrete values must be within the OWL axioms. The inferred concrete values are recorded in a new concrete relationships file. This is the format that will be used in the July 2021 International Edition and should be the format used by all national extensions produced thereafter.

We have just officially published a release of the OWL Toolkit for this: [Release 3.0.3](https://github.com/IHTSDO/snomed-owl-toolkit/releases/tag/3.0.3).

Kind regards,
Kai Kewley
