### ISSUE TITLE
Discrepancy in generation of owl file [State vs Inferred] [Ontoportal]

### ISSUE THREAD

**Issue by sumeetchhetri** [IHTSDO/snomed-owl-toolkit#80]
- Started with downloading Snomed Int 20230901 release along with UK Edition release files
- Then created owl file using 
```java -Xms4g -Xmx8g -jar snomed-owl-toolkit-3.0.6-executable.jar -rf2-to-owl -rf2-snapshot-archives SnomedCT_InternationalRF2_PRODUCTION_20230901T120000Z.zip,uk_sct2cl_36.4.0_20230802000001Z.zip,uk_sct2dr_36.5.0_20230830000001Z.zip```
- Uploaded this owl file to a local appliance of NCBO Ontoportal
- Looked up 24 hour urine lead output|391482006 in both the [live](https://bioportal.bioontology.org/ontologies/SNOMEDCT/?p=classes&conceptid=http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FSNOMEDCT%2F391482006&jump_to_nav=true#visualization) and local version of ontoportal 
  - Local Version screenshot
  - <img width="1432" alt="Bioportal_Local_ 391482006_SnomedINT20230901" src="https://github.com/IHTSDO/snomed-owl-toolkit/assets/1655705/ecc41916-ba29-4f72-adc9-9cd8e3d85cff">
  - Live Version screenshot
  - <img width="1432" alt="Bioportal_Live_ 391482006_UMLS_2023AA" src="https://github.com/IHTSDO/snomed-owl-toolkit/assets/1655705/45e03829-7811-437d-9a1b-514f9f711608">
- Stated Parent Hierarchy in Snowstorm
   - <img width="1432" alt="391482006_Stated_Snowstorm" src="https://github.com/IHTSDO/snomed-owl-toolkit/assets/1655705/78f2b477-3634-467d-8910-59d0eb1198e6">
- Inferred Parent Hierarchy in Snowstorm
  - <img width="1432" alt="391482006_Inferred_Snowstorm" src="https://github.com/IHTSDO/snomed-owl-toolkit/assets/1655705/0cf2a755-cd84-4c00-b68b-337d766e5e34">

Am assuming the toolkit generates the owl file based on Stated Relationships, how could an owl file be generated with Inferred Relationships so that the Tree Hierarchy resembles that of the Bioportal Environment?

**Comment by kaicode** [comment]
That is correct, the generated OWL ontology reflects the stated view of SNOMED CT using the axioms.
An OWL reasoner can be used to create inferred view. 

SNOMED International uses ELK version 0.4.3 to create the inferred hierarchy that is part of the inferred relationships distributed with the International Edition and most national Editions. NHS Digital produce the UK Edition but it's likely that they also use ELK.

ELK can be used to create the inferred view within Protégé, see [Getting Started > Reasoning](https://protegeproject.github.io/protege/getting-started/#reasoning)

The ELK Jar file also is available from Maven Central: [ELK OWL-API 0.4.3](https://repo1.maven.org/maven2/org/semanticweb/elk/elk-owlapi/0.4.3/elk-owlapi-0.4.3.jar). 

I am not aware of a standard way to distribute the inferred form using OWL functional syntax. My understanding is that OWL is for expressing the stated view only. Please correct me if I am wrong.

The SNOMED CT standard way to distribute the inferred view is using the [RF2 Inferred Relationship](https://confluence.ihtsdotools.org/display/DOCRELFMT/4.2.3+Relationship+File+Specification) file within the release archive.
