### ISSUE TITLE
Classifier creates empty classification files (when classifying an already classified release)

### ISSUE THREAD

**Issue by airaghavan** [IHTSDO/snomed-owl-toolkit#81]
Hello,

When I try to run the classification process using the following command, it generates a zip file with empty classification files.

`java --add-opens java.base/java.lang=ALL-UNNAMED -Xms4g -jar snomed-owl-toolkit-3.0.6-executable.jar -classify -rf2-snapshot-archives SnomedCT_InternationalRF2_PRODUCTION_20230901T120000Z.zip`

Could you please give me some hints on how to run the classifier?

I am using java 21.0.1 and `snomed-owl-toolkit-3.0.6-executable.jar` for this step.

`java 21.0.1 2023-10-17 LTS
Java(TM) SE Runtime Environment (build 21.0.1+12-LTS-29)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.1+12-LTS-29, mixed mode, sharing)`

Also, I see the following warning in the terminal.
`[WARN  ] [main] org.semanticweb.elk.reasoner.indexing.hierarchy.IndexObjectConverter - [reasoner.indexing.dataHasValue]ELK supports DataHasValue only partially. Reasoning might be incomplete! `

**Comment by kaicode** [comment]
Hi @airaghavan 

The classification function outputs the changes that are needed given the set of inputs. The inputs include the concepts, axioms and existing relationships within the RF2 release archive. When the classification function produces an empty relationships file that means that the sct2_Relationship files within the archive cover all the inferred relationships and no more.

That DataHasValue warning can be safely ignored, we tried to suppress that in the application but were not able to.

If you would like the classification process to produce the inferred relationships you could try an experiment. You could unzip the release archive, remove all the rows in the inferred relationships file, zip it up again and then run classification. Then we should expect all the original inferred relationships to be created in the output file. Please note that new relationships in the output do not contain a relationship identifier or module.

I hope that helps.
Kai Kewley
