### ISSUE TITLE
classify command

### ISSUE THREAD

**Issue by alePelus** [IHTSDO/snomed-owl-toolkit#86]
Hi!

I am having an issue with the classify tool (-classify)

So, as results of the clasification I am having 4 relationship (with active = 1) that are already inactivated in the last extension and it is re-activating these 4 relationship

It is possible that the classify tool is inferring the active=1 to the extension that I am classifying?

I would like to know what the classify tool do in the background in order to understand the process and try to find a solution for my problem...

so thank you in advance!

**Comment by kaicode** [comment]
I get the same 4 relationship changes when classifying just the international and SNS packages. This indicates that either the SNS 20231201 package is not classified correctly or that it was classified against a different version of the International Edition when the release was created.

**Comment by kaicode** [comment]
Are you in touch with the maintainers of the SNS package? I would recommend that they use this SNOMED OWL Toolkit to classify their release package to pick up inferred relationship changes to include in the package for publication.

It's possible to verify that a package contains all intended inferred relationship changes by using the classify function (as you have). There should be no inferred relationship changes.

**Comment by alePelus** [comment]
Hi!, 

No.. but we could ask.

I tried your recommendation like that:
- international edition July 2023
- A zip that contains 4 files of national (spain) extension (December 2023 already classified in order to see if it was classified correctly):
concepts snapshot, axiom OWL snapshot, Relationship snapshot and RelationshipConcreteValues snapshot.

And launch this command:
java -Xms2g -jar snomed-owl-toolkit-3.0.6-executable.jar -classify -rf2-snapshot-archives SnomedCT_International_Edition.zip,SNS.zip 

And I get in the relationship result file more than 3k relationships.... so that indicates that the spain national extension is not classified correctly? and that's derivate in an issue classifying the drug extension?

Thank you.

**Comment by alePelus** [comment]
Hi! There have been some changes/updates in the current version for the classify command in the toolkit? because I just tried to classify again the drug extension of january and I don't get the same result as the last month. And I have the exactly same files.... 

Thank you in advance.

**Comment by alePelus** [comment]
Hi,

I just discovered the issue!

It seems that the classify command doesn't see the content of the files in order to check if they are conceptos or axioms or relationship or relationshipConcreteValues... and you need to put the correct name to each file, and in this case I was using the name sct2_sRefset_OWLAxiomDelta_INT_20240201 for my OWL axiom file that I was classifying (becasue it was the name generated by the command -rf2-stated-to-complete-owl) but it seems that toolkit need the same with this format: sct2_sRefset_OWLExpression_SpainDrugExtensionSnapshot_ES_...
Because I saw in the log of the command when it was executing that with the old name it wasn't reading that file, but with the new names yes.

This is a normal behaviour? I thought that the toolkit checked the content of the files in order to see if they some type of file or another and not only the names of the files.

Thank you in advance.

**Comment by kaicode** [comment]
The toolkit is not able to write to a log file but depending on your operating system you may be able to capture the command output into a log file automatically. For example in Linux based systems like MacOS or Ubuntu the `tee` command can copy output to a log file while still streaming it to the terminal to see live.
```
java -Xms4g -jar snomed-owl-toolkit*executable.jar -classify -rf2-snapshot-archives SnomedCT_InternationalRF2.zip | tee output.txt
```

On Windows using PowerShell should also support this.
