### ISSUE TITLE
Build failure with 5.2.0

### ISSUE THREAD

**Issue by rwynne** [IHTSDO/snomed-owl-toolkit#91]
Hi all! I'm getting a build failure with the most recent checkout from Master. My last successful build was 5.1.0 so maybe this was introduced with 5.2.0? It's only seen as a Warning that later leads to failed Tests.

`[WARNING] Some problems were encountered while building the effective model for org.snomed.otf:snomed-owl-toolkit:jar:5.2.0
[WARNING] 'build.pluginManagement.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.jacoco:jacoco-maven-plugin @ org.snomed:snomed-parent-bom:3.2.0, /*****/*****/.m2/repository/org/snomed/snomed-parent-bom/3.2.0/snomed-parent-bom-3.2.0.pom, line 1094, column 25
`

**Comment by pgwilliams** [comment]
Hi @rwynne what you've sent us there is a warning, which I've also seen, and we'll follow up on that here (are you able to take a look at that @jimcornmell ?).   It doesn't result in a failing build when I've seen it.

But if you're _also_ seeing a build failure, is there some other message that relates to the failure reason?

**Comment by CoderMChu** [comment]
@rwynne I have fixed the issue in develop branch.

**Comment by rwynne** [comment]
@CoderMChu The develop branch is building for me. Thanks!

@pgwilliams The failure on master happens after the failed tests. Could it be because our Java is version 17? I know when running the toolkit we need to specify an "--add-opens" parameter. (We are unable to downgrade in our environment.)

The test errors (with -X option supplied) point to something similar:
`
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @a9cd3b1 [in thread "main"]
`

**Comment by pgwilliams** [comment]
Oh yes, that's the issue that that command line parameters fixes.   Very annoying to have to do that workaround.

--add-opens java.base/java.lang=ALL-UNNAMED
