### ISSUE TITLE
Management of the language refset for French in France

### ISSUE THREAD

**Issue by legallm** [IHTSDO/snomed-owl-toolkit#92]
Hi,

Is it possible to add management of the language refset for French in France (10031000315102), please?
The first French edition release is planned for June/July.

Thank you in advance!

**Comment by kaicode** [comment]
I've added the French language refset to the default config in the master and develop branches.
https://github.com/IHTSDO/snomed-owl-toolkit/commit/ae29812309681668c3498bafba64b70002335f98
