### ISSUE TITLE
SNOMEDCT with obsolete content

### ISSUE THREAD

**Issue by rwynne** [IHTSDO/snomed-owl-toolkit#94]
Hi all, Theoretical question before any experimentation. Is the toolkit capable of surfacing obsolete/inactive concepts in the OWL conversion? I'm considering an extraction of SNOMEDCT from the UMLS with this data and am just wondering if there would be any options to the toolkit or even data munging necessary to get the inactive content represented as defined classes (clinical drugs for my use case).

Thanks for any advice!

**Comment by kaicode** [comment]
The OWL Toolkit is actually quite bad at spotting inactive concepts. If there is an owl expression (axiom) that points to a concept that is inactive, or even does not exist, I believe the classification process does not fail.

In our infrastructure we rely on the Release Validation Framework to check for inactive concepts. Part of this is the [SNOMED Drools project](https://github.com/IHTSDO/snomed-drools) - this can run on the command line and can check for missing or inactive concepts within Axioms.
